[package]
name = "zdb-server"
description = "ZelligeDB server: REPL, TCP listener, Postgres wire protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "zdb_server"
path = "src/lib.rs"

[[bin]]
name = "zdb"
path = "src/main.rs"

[dependencies]
zdb-core = { workspace = true }
zdb-sql = { workspace = true }
